apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yfcj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0057-tenant/tkrw-pr712-0075-0057-app/devfile-sample-yfcj@sha256:d8ac95e35d65acaa3078839d4560db1bfa28550f55fb07029a144f4f9e92c41c
        name: my-nodejs
        resources: {}
status: {}
